### ISSUE TITLE
Typo in README.md - "Botcoin COre"

### ISSUE THREAD

**Issue by palfreman** [vertcoin-project/vertcoin-core#107]
"Vertcoin Core is based on Botcoin COre"

Is in doc/README.md.  My patch:

--- README.md	2020-05-01 22:35:11.474261381 +0100
+++ /tmp/README.md	2020-05-01 22:57:38.473594467 +0100
@@ -3,7 +3,7 @@
 
 Setup
 ---------------------
-Vertcoin Core is based on Botcoin COre, the original Bitcoin client and it builds the backbone of the network. It downloads and, by default, stores the entire history of Vertcoin transactions, which requires a few gigabytes of disk space. Depending on the speed of your computer and network connection, the synchronization process can take anywhere from an hour to a day or more.
+Vertcoin Core is based on Bitcoin Core, the original Bitcoin client and it builds the backbone of the network. It downloads and, by default, stores the entire history of Vertcoin transactions, which requires a few gigabytes of disk space. Depending on the speed of your computer and network connection, the synchronization process can take anywhere from an hour to a day or more.
 
 To download Vertcoin Core, visit [vertcoin.org](https://vertcoin.org/download-wallet/).

**Comment by metalicjames** [comment]
Please resubmit this as a pull request.
