### ISSUE TITLE
Uninstall Vertcoin Core

### ISSUE THREAD

**Issue by enrriquemicro** [vertcoin-project/vertcoin-core#116]
How can I uninstall the software and install it in another location?

Thank you.

**Comment by vertiond** [comment]
On Windows, all data is stored in your AppData folder.  Enter %APPDATA%\Vertcoin into Run.
On Linux, all data is stored in ~/.vertcoin

Back up wallet.dat from the Wallets folder and copy it over to the new location.  You may copy the Blocks and Chainstate folders over if you like, or let it sync from scratch.

**Comment by metalicjames** [comment]
Assuming solved, reopen if not.
