### ISSUE TITLE
Vertcoin core problem

### ISSUE THREAD

**Issue by Piskotovy** [vertcoin-project/vertcoin-core#119]
after years I turned on the tablet with the wallet and sent some VTC, it has been a week ago and i stiil dont receive the confirmation.  The wallet is trying to download two and half years old data but basically its doing nothing. i tryed to downloud uprage but the system is running on 32 bit and on the internet is all new VTC core only 64 bit. Do anybody know what should i do please? thank you for anyreply

**Comment by metalicjames** [comment]
We don't distribute 32-bit binaries anymore. You will either need to compile a version for yourself or switch to a 64-bit system.

**Comment by Piskotovy** [comment]
:) :) your repply reminds me one joke about IT guys because  is 100% correct but it totally suck :) :)
