### ISSUE TITLE
VTC transfer stuck on "unconfirmed"status -Electrum Tor wallet for 2 days

### ISSUE THREAD

**Issue by samnz001** [vertcoin-project/vertcoin-core#12]
### Describe the issue
I used the default fees to transmit a transaction and now it is stuck on "unconfirmed" for two days/

### Can you reliably reproduce the issue?
yes

#### If so, please list the steps to reproduce below:
1.send a large transaction with default fees
2.
3.

### Expected behaviour
Tell us what should happen
Could someone reject the transaction and i can resend it
### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:High Sierra 10.13.1
- CPU:1.3GHZ icore5
- RAM:4
- Disk size:256
- Disk Type (HD/SDD):SSD
![unconfirmed vtc](https://user-images.githubusercontent.com/25995145/32566488-f9099e48-c51c-11e7-9e30-6c233e2357e5.jpg)

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by metalicjames** [comment]
Wrong app.
