### ISSUE TITLE
RPC API no longer provides a canonical representation for "pubkey" outputs

### ISSUE THREAD

**Issue by fairglu** [vertcoin-project/vertcoin-core#125]
In v0.17 outputs of type pubkey no longer have an "addresses" fields, as in tx 32c9267a7659a17f397445ccce548b6ca2b6c514e50775bb04375074812f6a6e where you have

```
    {
      "value": 0.21763643,
      "n": 8,
      "scriptPubKey": {
        "asm": "0418a74130b2f4fad899d8ed2bff272bc43a03c8ca72897ae3da584d7a770b5a9ea8dd1b37a620d27c6cf6d5a7a9bbd6872f5981e95816d701d94f201c5d093be6 OP_CHECKSIG",
        "hex": "410418a74130b2f4fad899d8ed2bff272bc43a03c8ca72897ae3da584d7a770b5a9ea8dd1b37a620d27c6cf6d5a7a9bbd6872f5981e95816d701d94f201c5d093be6ac",
        "type": "pubkey"
      }
    },
```

This is an upstream change from bitcoin-core, but it does not alleviate the need to represent the output in explorer and other tools, it just makes it a "personal choice", while IMHO this should be standardized for a chain, and the wallet and its RPC API are a good place for this.

**Comment by metalicjames** [comment]
If that's a decision upstream has made, we're not going to change it here.
