### ISSUE TITLE
Issue building on Ubuntu 16.04 "undefined reference to `lyra2re_hash'"

### ISSUE THREAD

**Issue by hashbender** [vertcoin-project/vertcoin-core#13]
Hello, I see the following error during `make`.  This is on a vanilla Ubuntu 16.04 machine.  The autogen and configure steps succeed.  I am running --without-gui

```/home/luxor/C/vertcoin/src/primitives/block.cpp:32: undefined reference to `scrypt_N_1_1_256(char const*, char*, unsigned char)'
/home/luxor/C/vertcoin/src/primitives/block.cpp:28: undefined reference to `lyra2re_hash'
/home/luxor/C/vertcoin/src/primitives/block.cpp:24: undefined reference to `lyra2re2_hash'
collect2: error: ld returned 1 exit status
Makefile:3941: recipe for target 'test/test_bitcoin' failed
make[2]: *** [test/test_bitcoin] Error 1
make[2]: Leaving directory '/home/luxor/C/vertcoin/src'
Makefile:9733: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/luxor/C/vertcoin/src'
Makefile:746: recipe for target 'all-recursive' failed```

This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen
should build 

### Actual behaviour
Tell us what happens instead
doesn't build

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA. 
self-compiled

### Machine specs:
- OS: Ubuntu
- CPU: 
- RAM: 32Gb
- Disk size: 160Gb
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
NA

**Comment by metalicjames** [comment]
Fixed in e233f1fc3f752004189ef2a5601c4234d7ee55f6

**Comment by hashbender** [comment]
I have confirmed this is resolved.  Thank you @metalicjames
