### ISSUE TITLE
Building on Ubuntu 18.04

### ISSUE THREAD

**Issue by lurchinms** [vertcoin-project/vertcoin-core#140]
AR       leveldb/libmemenv.a
  AR       leveldb/libleveldb.a
/usr/bin/ld: vertcoin_cli-bitcoin-cli.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:7895: recipe for target 'vertcoin-cli' failed
make[2]: *** [vertcoin-cli] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: vertcoin_tx-bitcoin-tx.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:7899: recipe for target 'vertcoin-tx' failed
make[2]: *** [vertcoin-tx] Error 1
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/kriptokyng/miningcore_setup/tmp/vertcoin-core/src'
Makefile:17240: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/kriptokyng/miningcore_setup/tmp/vertcoin-core/src'
Makefile:781: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error

**Comment by vertiond** [comment]
You must either compile using the depends system or with https://github.com/vertcoin-project/vertcoin-core/pull/135

**Comment by vertiond** [comment]
Resolved via https://github.com/vertcoin-project/vertcoin-core/pull/135
