### ISSUE TITLE
Multi-screen issue; Not urgent

### ISSUE THREAD

**Issue by Meowdance** [vertcoin-project/vertcoin-core#141]
Not major bug - just interesting issue never seen with other program. Vertcoin Core exe does not like to be started from second screen. Whether on desktop, in file explorer or on USB stick - if I click icon on second monitor the program window will open outside of visible area and cannot be recovered. If the program is force quit and then move icon back on to main screen it will open fine. 

Click icon and program will open as usual - whichever screen it is on. 

If icon is clicked whilst on second screen program window will not be visible. 

https://user-images.githubusercontent.com/79007257/107850055-7b6ca700-6df7-11eb-943d-2c6f51188bc3.MP4

Happens any time the .exe icon is on the second monitor when clicked. 

0.17.1

Windows 10 / AMD 5800x

**Comment by vertiond** [comment]
If this issue persists, you should reproduce with Bitcoin-Core and submit this issue [upstream](https://github.com/bitcoin/bitcoin/) where there is a better chance of it being solved.
