### ISSUE TITLE
vertcoin transfer delays 2 days now to android wallet

### ISSUE THREAD

**Issue by bonsai282** [vertcoin-project/vertcoin-core#143]
![Screenshot_1](https://user-images.githubusercontent.com/79923980/109711515-a00ea000-7ba7-11eb-828f-eb49b103b23e.png)

I am new to this. I sent two days ago VTC to my android VTC wallet EDGE, defaiult comission. Status is "Sending", i have over 1.200 confirmations but still nothing received on EDGE

I expected immediate receipt

Nothng out of the ordinary occured, just VTC never arrived so far, its been 50 hours. All aspects doublechecked

24 hours after. i sent all my coins from OCM to my core wallet, all ok. I didnt try again to EDGE but i can. I just dont want to lose any VTC. 

Core downloaded from website, latest release.

I am using Win10, i5 10400, M2 500 gb Samsung, RX 570 4gb

Should i try again, or is there somehting i am missing?

**Comment by bonsai282** [comment]
wow. 4 days and no response. Great support, thank you guys!

**Comment by vertiond** [comment]
This is not Edge wallet support.

**Comment by vertiond** [comment]
Please contact Edge wallet for support.
