### ISSUE TITLE
Core wallet for Windows 32 bit

### ISSUE THREAD

**Issue by hosseinmor1** [vertcoin-project/vertcoin-core#15]
Hi,

Where can I get the latest core wallet for windows 32 bit?

thanks

**Comment by metalicjames** [comment]
We do not intend to support 32-bit builds from v0.12 onwards. 64-bit operating systems have been the standard for close to a decade now, either upgrade your computer/OS to 64-bit, compile 0.12 yourself for 32-bit or use v0.11.1 or previous for which we provided 32-bit builds.
