### ISSUE TITLE
RFE: port Berkeley DB C++ binding code to sqlite

### ISSUE THREAD

**Issue by kloczek** [vertcoin-project/vertcoin-core#153]
Recently only handful of project is still using BDB and IMO better would be switch to sqlite.

**Comment by vertiond** [comment]
Vertcoin-Core would gain this as part of rebasing from upstream Bitcoin-Core and would defer to their timetable.

**Comment by vertiond** [comment]
As of 0.18, SQLite is supported by compiling using `--with-sqlite` and is required for descriptor wallets.
