### ISSUE TITLE
0.17.1: wrong man pages names

### ISSUE THREAD

**Issue by kloczek** [vertcoin-project/vertcoin-core#154]
Looks like man pages are not under names `verticon*` but `bitcoin*`
```
$ rpm -ql vertcoin-core | grep man
/usr/share/man/man1/bitcoin-cli.1.gz
/usr/share/man/man1/bitcoin-qt.1.gz
/usr/share/man/man1/bitcoin-tx.1.gz
/usr/share/man/man1/bitcoin-wallet.1.gz
/usr/share/man/man1/bitcoind.1.gz
```

**Comment by YellowRoseCx** [comment]
that's because the wallet is using bitcoins source files as a fork but the name of the files do not hinder the performance of the wallet

**Comment by kloczek** [comment]
So after that fork those man pages can be renames and updated (?) :P

**Comment by vertiond** [comment]
Resolved by https://github.com/vertcoin-project/vertcoin-core/pull/175
