### ISSUE TITLE
 failed: Cannot assign requested address (99)

### ISSUE THREAD

**Issue by Stfb** [vertcoin-project/vertcoin-core#17]
### Describe the issue
I get connect errors in the debug.log. Like this one:
connect() to [2001:0:9d38:6abd:4f6:2cd5:f2c9:5cc4]:5889 failed: Cannot assign requested address (99)

### Can you reliably reproduce the issue?
Yes. Each time I run vertcoind.

### What version of bitcoin-core are you using?
vertcoind_0.12.0_amd64

### Machine specs:
- OS: Linux
- CPU: core i7 970
- RAM: 24GB

IPV6 it not activated on my router and server.
Any ideas?

Thanks,
Stephane.

**Comment by metalicjames** [comment]
This is normal. Since you likely do not have IPv6, you cannot connect to IPv6 nodes. The same behaviour is in upstream Bitcoin Core.

**Comment by Stfb** [comment]
Ok thanks! Looked like more an error than a fallback to IPV4...
