### ISSUE TITLE
Cant host Local P2Pool after Core 12.0 update

### ISSUE THREAD

**Issue by zstreet86** [vertcoin-project/vertcoin-core#18]
### Describe the issue
After updating to core wallet 12.0, can no longer host own node.

### Can you reliably reproduce the issue?
Yes, it just doesn't work (Local P2Pool).

#### If so, please list the steps to reproduce below:
1. Fresh install of core wallet 12.0 and OCM 1.1.6.
2. Local P2Pool node gives error "Only one usage of each socket address (protocol/network address/port) is normally permitted" when toggled to Network 2.

### Expected behaviour
Node should go from loading to running.

### Actual behaviour
Status stays at loading.

### Screenshots.
![image](https://user-images.githubusercontent.com/34562771/34028405-71b46b94-e128-11e7-8447-22d1457e3c0c.png)
![image](https://user-images.githubusercontent.com/34562771/34028410-7eaea7ba-e128-11e7-89a3-c3e78030a60c.png)
![image](https://user-images.githubusercontent.com/34562771/34028415-8602bfc4-e128-11e7-80bf-6d192b2a1a5a.png)

### What version of bitcoin-core are you using?
12.0 (latest)

### Machine specs:
- OS: Windows 10
- CPU: i7-3770
- RAM: 16 GB
- Disk size: 1TB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
OCM version 1.1.6. I can mine on other people nodes on network 2 no problem. Self node works fine on v11.X. When I open resmon.exe, it shows OCM is using ports 9181 and 9347 as expected.

**Comment by gu-ma** [comment]
Same issue. I've tried the one-click-miner and p2pool-vtc but it looks like p2pool is not compatible with the new wallet v12.0.

I've tried to launch the wallet v11.X instead but the v12.0 is already running (even when the app is closed it's running in the background) and it cannot "obtain a lock on data directory". 

If anyone knows how to stop the v12.0 and run v11.0 or even better on how to run p2pool with the wallet v12.0 it would be great 👍

**Comment by metalicjames** [comment]
The latest p2pool-vtc works with Core 0.12, there are several nodes hosting it. This seems like an OCM specific issue.

**Comment by zstreet86** [comment]
Hi James, I disagree. Because if I roll back to 11.0 wallet, and change nothing on the miner, it works. How can you straight up close the ticket without even trying to resolve it? Typically tickets dont get closed until they are resolved and or the user is satusfied.

l went out of my way to try and provide feedback, write up the ticket and it is straight up dismissed. I am just trying to help make Vert a better product.

Also, I have 2 friends with the EXACT same issue. It will need to be fixed before it goes mainstream. I have seen multiple people ask about this in the tech support channel as well. We all ended up rolling back to 11.0 to "fix it".

After being stumped and unsuccessfully trying to help me troubleshoot, Jin (mod on Discord) asked me to write this ticket.

Good luck,

Discord Name - Ritzypoo
________________________________

**Comment by stevecastaneda** [comment]
OCM launches a version of P2Pool that is only compatible with 11.0.  That's why rolling back to 11 fixes your issue, and upgrading to 12 breaks it.

When OCM upgrades the P2Pool version to the latest pre-release, compatible with Wallet 12.0, OCM will then be able to start the node like you want. 

Until then, you can manually launch a node but it's not nearly as easy as OCM makes it.  My recommendation would be to stay on 11.0 wallet until OCM updates.
