### ISSUE TITLE
P2Pool stopped working with current version

### ISSUE THREAD

**Issue by Strunczez** [vertcoin-project/vertcoin-core#189]
Getting stratum line error in miner connected to my P2Pool node

**Comment by vertiond** [comment]
Please direct p2pool related questions to its [relevant repository](https://github.com/vertcoin-project/p2pool-vtc) with more information like environment and logs.

**Comment by Strunczez** [comment]
Problem still persists with recent update
before 18.0 there were no issues with p2pool <> core, so I was able to create my own p2pool and mine on it.
After 18.0 update, Verthash miner connected to my p2pool node is line by line writing "stratum line error"
please check if something did not went wrong in code responsible with connections to core which are used by p2pool

**Comment by vertiond** [comment]
Was possibly addressed in https://github.com/vertcoin-project/p2pool-vtc/commit/5502f26b4ef754ef3945bcbe5113ce388021a4e4

Please try the master branch. This issue belongs on the p2pool-vtc repository.
