### ISSUE TITLE
Slow startup on new version

### ISSUE THREAD

**Issue by navidrasi** [vertcoin-project/vertcoin-core#19]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
New version takes too much time to start , here is the logs 
2017-12-13 03:48:26 Using obfuscation key for C:\d\data\blocks\index: 0000000000000000
2017-12-13 03:50:07 Compacting 1@0 + 8@1 files

another example:

2017-12-14 17:17:30 Using obfuscation key for C:\d\data\blocks\index: 0000000000000000
2017-12-14 17:19:13 Compacting 1@0 + 8@1 files

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1.close the core and run it again 

### Expected behaviour
Slow start up

### Actual behaviour
it use to take less than 10 s to start now more than 3 min 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Windows 10
- CPU: Core i5
- RAM:8GB
- Disk size:500GB
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by metalicjames** [comment]
This is confirmed, though the reason for the slowdown is as of yet unclear.

**Comment by bartenbach** [comment]
+1 Noticeable slowdown.  No idea why though.

**Comment by knightorc** [comment]
+1 Any update on the status?

**Comment by gertjaap** [comment]
The slowdown is caused by the full proof-of-work verification on startup. This was actually disabled in 0.11 (probably because of the same performance reasons). But it's important to check the chain of work on startup. So we'll have to improve the performance of those checks, in the meanwhile i created a command-line switch to skip the verification if you're in a hurry.

**Comment by gertjaap** [comment]
Update: this new version doesn't seem to have the SSE2 optimized Scrypt routines enabled. Fixing that. Takes about 30 seconds (25%) off the startup time on a full verification. But it's still too slow. Looking at other avenues to pursue, stay tuned.

**Comment by gertjaap** [comment]
Update: changed the default behavior to rely on the checkpoints, and do PoW verification only after the last known checkpoint. This reduces the startup time by roughly 90%. It's still possible to do full verification if desired.

**Comment by metalicjames** [comment]
Fixed in #33
