### ISSUE TITLE
Items for packaging

### ISSUE THREAD

**Issue by vertiond** [vertcoin-project/vertcoin-core#190]
- Add https://github.com/bitcoin/bitcoin/blob/master/contrib/init/ and brand for Vertcoin
- Add [vertcoin.svg](https://github.com/vertcoin-project/vertcoin-logo-package/blob/master/svg/logo/vertcoin.svg) to https://github.com/vertcoin-project/vertcoin-core/tree/master/src/qt/res/src
- Brand https://github.com/vertcoin-project/vertcoin-core/blob/master/share/examples/bitcoin.conf for Vertcoin

**Comment by cruelnovo** [comment]
Created PR#193 to add (and rename to vertcoin) the init scripts from bitcoin & add vertcoin.svg
