### ISSUE TITLE
Vertcoin Core (vertoinc qt.exe) won launch anymore - used to be fine

### ISSUE THREAD

**Issue by VioletBlue007** [vertcoin-project/vertcoin-core#191]

**Comment by VioletBlue007** [comment]
Error: Cannot obtain a lock on data directory. <dir_path... OCM>, Vertcoin Core is probably already running.

VC is definitely not already running, the miner is but not Core.
What is this issue and how do you fix it?

**Comment by vertiond** [comment]
Find the running process and kill it.  Alternatively, restart your computer.
