### ISSUE TITLE
Please wait for pending payout infomation

### ISSUE THREAD

**Issue by solar1pv** [vertcoin-project/vertcoin-core#202]
My vertcoin miner says"Please wait for pending payout information" 
When I click on send coins and enter my wallet address, and it says " invalid address". 
My spendable balance is ~ 16. 0
What do i need to do to transfer my balance to Atomic wallate or Coinbase?

**Comment by vertiond** [comment]
Make sure it's a vertcoin address you are sending to.  Neither atomic wallet nor coinbase support vertcoin. Use https://github.com/vertcoin-project/one-click-miner-vnext/issues for future issues.

**Comment by solar1pv** [comment]
Thank you. 
Which wallet do you recommend that works best for Vertcoin ?
