### ISSUE TITLE
Branches and tag name collision

### ISSUE THREAD

**Issue by kloczek** [vertcoin-project/vertcoin-core#204]
Looks like the same tags names and branches are causing issues on downloading taggeg tar balls
https://support.github.com/ticket/personal/0/1733894

**Comment by vertiond** [comment]
I've noticed this while packaging for other operating systems.  Looks like bitcoin always uses `v` prefix in tags to avoid any confusion. Unless I hear otherwise, I'll begin modeling their exact scheme from now on.

**Comment by kloczek** [comment]
What about add v prefixed tag for latest version? (it sould enough)

**Comment by vertiond** [comment]
Tags can't be modified retroactively and other platforms/packagers depend on the existing naming structure.

**Comment by kloczek** [comment]
Of course it can be.
Just delete tag->  add new one on the same has -> git push.
Other thing that I've asked about **add** v tag on the same hash.

**Comment by vertiond** [comment]
That would break every platform and packager that depends on the existing structure.

**Comment by kloczek** [comment]
Adding tag break something? 🤔 
How?

**Comment by vertiond** [comment]
I believe it would change the download link path from 
`https://github.com/vertcoin-project/vertcoin-core/releases/download/19.0-rc1/vertcoin-19.0-rc1-win64-setup.exe`
to 
`https://github.com/vertcoin-project/vertcoin-core/releases/download/v19.0-rc1/vertcoin-19.0-rc1-win64-setup.exe`

**Comment by vertiond** [comment]
`https://github.com/vertcoin-project/vertcoin-core/archive/refs/tags/19.0-rc1.tar.gz`
to
`https://github.com/vertcoin-project/vertcoin-core/archive/refs/tags/v19.0-rc1.tar.gz`

This means that all existing integrations must be modified and why it won't be changed retroactively but is something that can be done in the future.

**Comment by vertiond** [comment]
Is there something you are trying to do that isn't working with the current naming convention?  If not, this isn't so much of an issue.  The support link in the OP is broken, too.

**Comment by kloczek** [comment]
> Is there something you are trying to do that isn't working with the current naming convention? If not, this isn't so much of an issue. The support link in the OP is broken, too.

Yes and everything is described in gihub ticket which I've mention opening this tisket.

**Comment by vertiond** [comment]
https://github.com/vertcoin-project/vertcoin-core/releases/tag/v22.1rc1
https://github.com/vertcoin-project/vertcoin-core/tree/22.x
