### ISSUE TITLE
need help running vertcoin wallet for solo mining

### ISSUE THREAD

**Issue by alptolga** [vertcoin-project/vertcoin-core#206]
Hi, I need help to configure vertcoin wallet for solo mining. Can you help me?
I  started the vertcoin-qr in my ubuntu machine and I want to connect my rigs to it but I couldn^t be successfull.

**Comment by vertiond** [comment]
Please join the vertcoin discord or reddit for support https://discord.gg/vertcoin https://reddit.com/r/vertcoin

**Comment by alptolga** [comment]
I have already joined discord  but I couldn't get any information from there.
