### ISSUE TITLE
First breakdown in 2 years of experience

### ISSUE THREAD

**Issue by tomberuk** [vertcoin-project/vertcoin-core#228]
The first obvious attempts at repair failed. It crashes at the startup stage, or rather the creation of the blockchain core.

Tomas: "This is the mistake. " - Mastodon on ZHub
https://zhub.link/@tomberuk/109782197462188021

**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by vertiond** [comment]
Hi! I would try to reindex. That can be done by going into `C:\Program Files\Vertcoin` and running `.\vertcoin-qt.exe -reindex` from a command prompt.
