### ISSUE TITLE
Spendable balance 0.0000 the last 24 hrs 2.33MH/s

### ISSUE THREAD

**Issue by solar1pv** [vertcoin-project/vertcoin-core#232]
#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by solar1pv** [comment]
OS W-7 Last 24 hrs mining and my spendable balance says 0.0000 
2 video cards MH/s solid 2.33MH/s 
Why is spendable balance not going higher than 0.000?
Yesterday I reinstalled Virtcoin one click miner and still says ~0.0000 and MH/s is still 2.33. 
I don't know what to do next to fix it? 
Clicked on refresh many time and still shows 0.0000. 

Thank you, 
Robert & Elena

**Comment by vertiond** [comment]
Use https://github.com/vertcoin-project/one-click-miner-vnext/issues
