### ISSUE TITLE
RegTest Regression Test Network Broken - Genesis Block Assertion Failure

### ISSUE THREAD

**Issue by protonioneutron** [vertcoin-project/vertcoin-core#24]
### Describe the issue
Regtest Genesis Block Assertion Fails

vertcoind: ../../src/chainparams.cpp:303: CRegTestParams::CRegTestParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206")' failed.

#### If so, please list the steps to reproduce below:
1. Set regtest=1
2. Run vertcoind
3. Get Assersion Failure

### What version of bitcoin-core are you using?
Vertcoin Core Daemon version v0.12.0.0-d2a8ef4

### Machine specs:
Linux ex1 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

**Comment by protonioneutron** [comment]
PR #28 fix is working for me.

**Comment by metalicjames** [comment]
https://github.com/vertcoin-project/vertcoin-core/pull/28 merged now
