### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by sr005307** [vertcoin-project/vertcoin-core#29]
On vertcoin-core repo,,,
I've seen this : [[[We would be grateful to those who can help port the existing Bitcoin Core test cases to Vertcoin such that they can be used to assure correctness.]]]

So, How can I do this? more detailed explanations?
I want to help you

**Comment by metalicjames** [comment]
The testing files in the `tests` subdirectory are presently configured for Bitcoin's network and properties. Some of the tests need to be modified so that they pass for Vertcoin's network.
