### ISSUE TITLE
ERROR error -32601: method not found

### ISSUE THREAD

**Issue by goodthebest** [vertcoin-project/vertcoin-core#35]
@vertcoin-project dev attention please

I'm trying to add vertcoin into yiimp and keep getting this error

>ERROR error -32601: method not found yiimp

I suspect your fork is different from other and even this doesn't work 
`./vertcoin-cli getinfo`
until I add - before getinfo.
`./vertcoin-cli -getinfo`

What can be done to add it into yiiimp, perhaps you need to add some pull request at yiiimp for this fix?
https://github.com/tpruvot/yiimp/pulls

**Comment by metalicjames** [comment]
This is inherited from upstream Bitcoin, where `getinfo` has been deprecated. Yiimp need to update if they want to support new software. Otherwise you can use old wallet versions.
