### ISSUE TITLE
KGW diff algorithm

### ISSUE THREAD

**Issue by cryptozeny** [vertcoin-project/vertcoin-core#36]
Hello I am writing here for the first time. I have a question about the difficulty adjustment algorithm. 

Algorithms include you can use:

> DGW,

> DigiShield 

> and KGW. 

I would to know why did you choose KGW? @metalicjames If so, what are the advantages compared to other algorithms? Thank you for reading.

**Comment by sr005307** [comment]
Well. those questions are not related to developement....

Those are about economics.

**Comment by metalicjames** [comment]
Agree.

**Comment by cryptozeny** [comment]
i am sorry about not dev related question. however i would to know about this. now i am studying vertcoin. where is the good place to ask?

**Comment by ghost** [comment]
https://github.com/vertcoin-project/VertDocs

**Comment by cryptozeny** [comment]
@eliaswinnard thanks for the link, but there is no info about KGW...

**Comment by ghost** [comment]
https://bitcoin.stackexchange.com/questions/21730/how-does-the-kimoto-gravity-well-regulate-difficulty
