### ISSUE TITLE
Generated receiving address not starting with letter "V"

### ISSUE THREAD

**Issue by Strunczez** [vertcoin-project/vertcoin-core#48]
I recently switched to 13.1 and generated receiveing address is not starting with letter "V" is this correct?

**Comment by metalicjames** [comment]
That is correct. The new format is the `vtc1q` prefixed bech32 segwit addresses which you should use instead. In the case you need an old wallet to send to you, use the `3` prefixed P2SH address.

**Comment by Strunczez** [comment]
Ahh ok. I do not know that.
p2pool which I use does not work with thoose new adresses.

**Comment by metalicjames** [comment]
We're working on upgrading P2Pool to support the new address format. In the meantime you can generate a `V` address from the debug console using `getnewaddress "" legacy`.

**Comment by Strunczez** [comment]
Downloaded 12.0 generated new address, switched to 13.1 and everything is OK.

**Comment by Strunczez** [comment]
I will write an Email to You about programing from address lukasz.m<cut>@gmail.com

**Comment by dustinmichels** [comment]
Hi! Can I check on the status of this? Is it possible to mine in a P2Pool now with a 3 prefixed VertCoin address?

**Comment by xtjie** [comment]
Thanks,it is work! getnewaddress "" legacy

**Comment by BigBil** [comment]
it does not work for me, I get the following message


11:17:48
￼
getnewaddress "" legacy.


11:17:48
￼
Unknown address type 'legacy.' (code -5)


11:22:37
￼
getnewaddress "" legacy


11:22:37
￼
Method not found (code -32601)
