### ISSUE TITLE
Testnet verificationprogress problem

### ISSUE THREAD

**Issue by enertom** [vertcoin-project/vertcoin-core#50]
Hi, i have blocks === headers, but `verificationprogress` is 0.9955239941455529
where is the problem?

https://i.imgur.com/djQaqOO.png

**Comment by metalicjames** [comment]
I don't see the issue here. There are probably not any miners on testnet hence the long time since the last block.

**Comment by enertom** [comment]
Hm... I think it's issue, getblocktemplate return:
`
./vertcoin-cli getblocktemplate
error code: -10
error message:
Vertcoin is downloading blocks...
`

**Comment by brandoncurtis** [comment]
@enertom, what block are you stuck on for the testnet, and what version of Vertcoin are you running?

I'm stuck here:
```
Loaded best chain: hashBestChain=25a98f05d2399ae0b8dd3a55eb290973ee2340a621ac83dc03892a0a3f32cf46 height=107296 date=2018-05-25 22:22:27 progress=0.989043
```

I'm running `Vertcoin Core version v0.13.2.0-bc60034 (release build)` built from source and I'm running it with:
```
vertcoind -printtoconsole -txindex -dbcache=1024 -testnet -addnode=tvtc.blkidx.org:5889
```
