### ISSUE TITLE
Option -maxconnections does not seem to be working

### ISSUE THREAD

**Issue by seungjlee** [vertcoin-project/vertcoin-core#52]
Even when I set -maxconnections=25, I usually get over 120 connections in my server. I don't usually mind the high traffic but I would like to lower it since it can cause too much lag when connections are downloading the whole blockchain. I hope to find a solution quick for this or I will be forced to just block incoming connections.

**Comment by metalicjames** [comment]
Is this still a problem for you?

**Comment by seungjlee** [comment]
I have gotten around the problem by setting maxconnections in the configuration file instead.
