### ISSUE TITLE
Not sign message 

### ISSUE THREAD

**Issue by zijieli111** [vertcoin-project/vertcoin-core#53]
The entered address does not refer to a key .please check the address and try again.

**Comment by metalicjames** [comment]
I'm assuming you tried to use a `3` profixed P2SH address. Those cannot be signed with. You'll need to use a `vtc1q` prefixed segwit address or legacy `V` P2PKH address.

**Comment by tasinttttttt** [comment]
how can one do to generate the `vtc1q` address then from vertcoin core ?

**Comment by metalicjames** [comment]
Check the "Generate bech32 address" box on the address creation screen.
