### ISSUE TITLE
Transaction CSV export enhancement

### ISSUE THREAD

**Issue by nickhoyt** [vertcoin-project/vertcoin-core#6]
### Describe the issue
CSV currently exports only the entire transaction log of the wallet

### Expected behaviour
CSV export should give an option to:
export a date/time range
export all from last csv export
export all 

### Actual behaviour
CSV has no option to export a range so it always exports all

This is an enhancement request for the Qt GUI

**Comment by sr005307** [comment]
I think I could help solving this.

Let me know which file...

Also do you have a captured img?

**Comment by metalicjames** [comment]
A captured image? What do you mean?

**Comment by metalicjames** [comment]
I think this feature request would be better suited for upstream Bitcoin Core.
