### ISSUE TITLE
Bryangoodson.org DNS lookup for seed is failing

### ISSUE THREAD

**Issue by cruelnovo** [vertcoin-project/vertcoin-core#61]
src.chainparams.cpp has the following line:
vSeeds.emplace_back("seed.vtc.bryangoodson.org"); // Bryan Goodson

It is failing DSN resolution.  Not sure if there is a “fix” for this... but, wanted to make the dev team aware.

**Comment by Bryangoodson** [comment]
Not sure why its failing, but I'm going to take this server down pretty soon. Getting too expensive. @metalicjames safe to remove this seed from the list.

**Comment by metalicjames** [comment]
Bryan's DNS seed will be removed in the next release.
