### ISSUE TITLE
problem with p2pool since upgrading to vertcoin core v 0.13

### ISSUE THREAD

**Issue by Mahuro** [vertcoin-project/vertcoin-core#65]
Hi there,

I hope you can help... I am running a mining rig on ubuntu I noticed that at some point my wallet was having issues and I found out there was v013 out and it was suggested to upgrade...I did but since then it seems that p2pool can't run with that wallet?...first was the problem with the new addresses and then after figuring out to generate a legacy address that p2pool could recognize and run, after mining for a whole week nothing was added to my wallet i usually mine 10 coins a week or more. Also I sent 60 coins to another address and they are lost in limbo...

My questions are: 
1-  is there incompatibility between the new vo13 wallet and p2pool?
2- do i need to re-compile p2pool to work with the new wallet?
3- can't I simply keep using the old wallet?

I'll appreciate your advice about the best and mos efficient setup,

Thanks,

Mauricio.

**Comment by metalicjames** [comment]
Only version 0.13.3 should be used on the network, previous versions are vulnerable to the inflation bug from upstream Bitcoin Core. The latest P2Pool works with 0.13.3 and supports bech32 addressses. Join the Discord if you need additional setup assistance.

**Comment by Mahuro** [comment]
Hi James...
Thank you ill try that.
Also how can I join the discord as you memtioned? Ill appreciate sharing
experiences with mining.

Thanks.

**Comment by metalicjames** [comment]
https://discord.gg/vertcoin
