### ISSUE TITLE
Some one is forging the blocks. Beware of double spending attack

### ISSUE THREAD

**Issue by a1binos** [vertcoin-project/vertcoin-core#67]
Hi.
Yesterday, someone forged 100+ blocks, erasing all other mined blocks.
attacker address is VvqbVNGE5ePrsvbgmRSpycdhoJUb9Myarg

**Comment by a1binos** [comment]
update: 300++ blocks. Possible exchange attack!

**Comment by metalicjames** [comment]
It's unfortunate, but not a bug.
