### ISSUE TITLE
Cannot compile Vertcoin Core on Ubuntu 18.04

### ISSUE THREAD

**Issue by coin2** [vertcoin-project/vertcoin-core#79]
I am trying to compile Windows build of Vertcoin Core on Ubuntu 18.04 (virtualbox) according to the instructions at https://github.com/vertcoin-project/vertcoin-core/blob/master/doc/build-windows.md

Every time I encounter the same error (see below). Here, first of all, is the steps I take to build.

I first install dependencies as instructed:

sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl

I set these to posix:
sudo update-alternatives --config x86_64-w64-mingw32-g++
sudo update-alternatives --config x86_64-w64-mingw32-gcc

Install these:
sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev

I download vertcoin core (master) from github into /usr/src/vertcoin-core/

Then I make using:
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh # not required when building from tarball
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make

The error I enounter is:
crypto/.libs/libbitcoinconsensus_la-scrypt.o:scrypt.cpp:(.text.startup+0x17): undefined reference to `boost::system::generic_category()'
crypto/.libs/libbitcoinconsensus_la-scrypt.o:scrypt.cpp:(.text.startup+0x1c): undefined reference to `boost::system::generic_category()'
crypto/.libs/libbitcoinconsensus_la-scrypt.o:scrypt.cpp:(.text.startup+0x21): undefined reference to `boost::system::system_category()'
primitives/.libs/libbitcoinconsensus_la-block.o:block.cpp:(.text+0x1cb): undefined reference to `Params()'
primitives/.libs/libbitcoinconsensus_la-block.o:block.cpp:(.rdata$.refptr._ZN16CBaseChainParams7TESTNETB5cxx11E[.refptr._ZN16CBaseChainParams7TESTNETB5cxx11E]+0x0): undefined reference to `CBaseChainParams::TESTNET[abi:cxx11]'
collect2: error: ld returned 1 exit status
Makefile:3704: recipe for target 'libbitcoinconsensus.la' failed
make[2]: *** [libbitcoinconsensus.la] Error 1
make[2]: Leaving directory '/usr/src/vertcoin-core/src'
Makefile:9866: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/vertcoin-core/src'
Makefile:748: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

The generated compiler options look like this:
  with wallet   = yes
  with gui / qt = yes
    qt version  = 5
    with qr     = yes
  with sse2     = no
  with zmq      = yes
  with test     = yes
  with bench    = yes
  with upnp     = yes
  use asm       = yes
  debug enabled = no
  werror        = no

  target os     = windows
  build os      = 

  CC            = /usr/src/vertcoin-core/depends/x86_64-w64-mingw32/share/../native/bin/ccache x86_64-w64-mingw32-gcc
  CFLAGS        = -pipe -O2  -fPIC
  CPPFLAGS      = -I/usr/src/vertcoin-core/depends/x86_64-w64-mingw32/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -D_MT -DWIN32 -D_WINDOWS -DBOOST_THREAD_USE_LIB -D_FILE_OFFSET_BITS=64
  CXX           = /usr/src/vertcoin-core/depends/x86_64-w64-mingw32/share/../native/bin/ccache x86_64-w64-mingw32-g++ -std=c++11
  CXXFLAGS      = -pipe -O2 
  LDFLAGS       = -L/usr/src/vertcoin-core/depends/x86_64-w64-mingw32/share/../lib 
  ARFLAGS       = cr

I have tried various flags / installing extra dependencies etc but nothing seems to get me past this error. What am I doing wrong? I have been able to compile litecoin core successfully, but vertcoin core does not seem to work for me.

**Comment by coin2** [comment]
I've figured it out, so I'm closing this ticket.

**Comment by petrkr** [comment]
And will you tell others how did you figured out? So if someone have same problem they will read it here ?

Thanks

**Comment by hjbolide** [comment]
Hi @coin2, can you please share what's the solution here?
