### ISSUE TITLE
Vertcoin-QT Isn't Building But the Rest of the Executables Are

### ISSUE THREAD

**Issue by panda2k** [vertcoin-project/vertcoin-core#8]
When building Vertcoin-qt on arch linux with `./autogen.sh` `./configure` then `make` everything builds in the `src` directory (vertcoind, vertcoin-cli, vertcoin-tx) but Vertcoin-QT is not. I have the QT dependencies installed (qt5) and I have tried building with `./configure --with-gui` but that doesn't help.

**Comment by metalicjames** [comment]
What is the final configuration output for `./configure`?

**Comment by spresnal** [comment]
Issue with the make script?

**Comment by panda2k** [comment]
Here is the final config log output. 
```Options used to compile and link: 
 with wallet        = yes
      qt version    = 5
      with qr         = yes
  with zmq         = yes
 with test           = yes
 with bench       = yes
 with upnp         = yes
 debug enabled = no
 target os           = linux
 build os             =

 CC                     = gcc
 CFLAGS            = -g -02 -fPIC
 CPPFLAGS       = -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
 CXX                  = g++
 CXXFLAGS       = -I/usr/include/openssl-1.0
 LDFLAGS          = -L/usr/lin/openssl-1.0 -lssl ```

**Comment by metalicjames** [comment]
Hmm. That all looks okay. Have you checked inside the `src/qt` dir? I suspect the binary will be in there.

**Comment by panda2k** [comment]
Thanks! It is there, guess I messed up my search command for Vertcoin-QT.
