### ISSUE TITLE
MultiAlgo Vertcoin

### ISSUE THREAD

**Issue by ChillingSilence** [vertcoin-project/vertcoin-core#82]
Hi Team,

I think Vertcoin have an opportunity here with both Verthash and Lyra2REv3 to increase their security, while maintaining their GPU mining ethos.

Lyra2REv3 is great because it's available now, but it can be mined on rent-a-hash websites. This presents an issue when you can rent enough hash power to double-spend, hence the teams desire for Verthash.

I think it's worth the team investigating a MultiAlgo implementation, such as Huntercoin first had (SHA256 + Scrypt), but with Verthash, Lyra2REv3, and possibly even a 3rd.

This issue is raised to begin fostering some discussion, with the goal of maintaining Vertcoin's priority of decentralization, GPU mining, while also looking further into the security aspects.

EDIT: Also worth the plug to mention DigiShield (MultiShield) for realtime difficulty adjustment can basically be pinched from DigiByte 😇

**Comment by vertiond** [comment]
Related PR https://github.com/vertcoin-project/vertcoin-core/pull/100

Future discussions can take place [here](https://github.com/vertcoin-project/vertcoin-core/discussions)
