### ISSUE TITLE
ERROR error -32601

### ISSUE THREAD

**Issue by metalik88** [vertcoin-project/vertcoin-core#85]
Please tell me how to fix
ERROR error -32601: getinfo this call was removed in version 0.16.0. use the appropriate fields from: - getblockchaininfo: blocks, difficulty, chain - getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings - getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion vertcoin-cli has the option -getinfo to collect and format these in the old format.

**Comment by metalicjames** [comment]
`getinfo` was removed in newer versions of Core. You will need to use the other RPC calls it suggests, or `-getinfo`.
