### ISSUE TITLE
Vertcoin file hashes and signatures ??

### ISSUE THREAD

**Issue by ghost** [vertcoin-project/vertcoin-core#9]
If i havent missed anything, one would think that the downloads under: https://github.com/vertcoin/vertcoin/releases would have hashes and signatures to verify the files.  Please can you provide the necessary security verifications?

**Comment by metalicjames** [comment]
Most recent release has signatures for the binaries now.

**Comment by ghost** [comment]
thank you!

**Comment by ghost** [comment]
Will you be providing hashes of the files as well?
